- name: myorg-registration.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      required: Y
    registration_date:
      required: Y
    entity_type:
      required: Y
    entity_status:
      required: Y
    entity_status_effective:
      required: Y
    entity_name_effective:
      required: Y
    address_line_1:
      required: Y
    address_line_2:
      required: Y
    addressee:
      required: Y
    city:
      required: Y
    country:
      required: Y
    legal_name:
      required: Y
    postal_code:
      required: Y
    province:
      required: Y
    effective_date:
      required: Y
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      required: N

- name: myorg-tax.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      required: Y
    tax_number:
      required: Y
    effective_date:
      required: Y

- name: myorg-liquor.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      required: Y
    license_number:
      required: Y
    dancing_permitted:
      required: Y
    patio:
      required: Y
    effective_date:
      required: Y
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      required: N

- name: myorg-credential.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      description: Unique identifer assigned to entity by registrar (requires an existing registration credential)
      required: Y
    tax_number:
      description: Relevant tax number
      required: Y
    license_number:
      description: Relevant liquor license number
      required: Y
    credential_status:
      description: Status of the credential (ACTive or HIStorical)
      required: Y
    credential_status_effective:
      description: Date status became/becomes effective (e.g. can be future dated)
      required: Y
    credential_status_expiry:
      description: Date status will expire
      required: N
    effective_date:
      description: Date Credential is effective (typically same as date credential is issued)
      required: Y
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      required: N

